export enum RouteTypes {
	Dashboard = "/",
	VaultCreate = "/create",
	VaultCreateBasic = "/create/basic",
	VaultCreateComment = "/create/comment",
	VaultCreateKeySource = "/create/key-source",
	VaultCreateKeyManual = "/create/key-manual",
	VaultCreateEntropyGen = "/create/entropy-gen",
	VaultCreateSplitToggle = "/create/split-toggle",
	VaultCreateSplitConfig = "/create/split-config",
	VaultCreateIntegrity = "/create/integrity",
	VaultCreateIntegrityPassword = "/create/integrity-password",
	VaultCreateOutput = "/create/output",
	VaultCreateOutputFile = "/create/output-file",
	VaultCreateSummary = "/create/summary",
	VaultCreateEncryptRun = "/create/encrypt-run",
	VaultOpen = "/open",
	VaultOpenContainer = "/open/container",
	VaultOpenPassword = "/open/password",
	VaultOpenShamir = "/open/shamir",
	VaultOpenShamirMethod = "/open/shamir-method",
	VaultOpenShamirFile = "/open/shamir-file",
	VaultOpenIntegrity = "/open/integrity",
	VaultOpenSummary = "/open/summary",
	VaultOpenRun = "/open/run",
	ContainerDetails = "/container/:id",
}
